networks:
    backend:
        driver: bridge

services:
    db:
        image: postgres:14-alpine
        container_name: postgres
        hostname: postgres
        restart: always
        env_file:
            -   path: .env
                required: true
        #ports:
        # - 5432:5432 # descomentar para acceder a la base de datos desde el host
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - backend

    backend:
        image: marcasautos-api
        container_name: api
        hostname: api
        restart: always
        depends_on:
            - db
        ports:
            - 8080:8080
            - 8081:8081
        build:
            context: .
            dockerfile: MarcasAutos.Api/Dockerfile
        env_file:
            -   path: .env
                required: true
        networks:
            - backend

    test:
        image: test
        build:
            context: .
            dockerfile: MarcasAutos.Test/Dockerfile
        depends_on:
            - db
        networks:
            - backend

volumes:
    postgres-data:
        driver: local
        driver_opts:
            type: none
            device: ./Postgres/data
            o: bind